development:
  adapter: postgresql
  database: abonmaan_db
  user: amvaleh
  password: postgresql810190501
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: abonmaan_db
  user: amvaleh
  password: postgresql810190501
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: abonmaan_db
  user: amvaleh
  password: postgresql810190501
  pool: 5
  timeout: 5000
