development:
  :address: smtp.khetabeghadir.com
  :port: 465
  :authentication: plain
  :user_name: ab@khetabeghadir.com
  :password: bgDh0$96
  :authentication: login
  # :ssl: true
  # :tls: true
  :enable_starttls_auto: true
production:
  :address: smtp.khetabeghadir.com
  :port: 465
  :authentication: plain
  :user_name: ab@khetabeghadir.com
  :password: bgDh0$96
  :authentication: login
  # :ssl: true
  # :tls: true
  :enable_starttls_auto: true
