development:
  :address: mail.khetabeghadir.com
  :port: 25
  :user_name: ab@khetabeghadir.com
  :password: bgDh0$96
  :authentication: login
  # :enable_starttls_auto:  true
production:
  :address: mail.khetabeghadir.com
  :port: 25
  :user_name: ab@khetabeghadir.com
  :password: bgDh0$96
  :authentication: login
  # :enable_starttls_auto:  true
