development:
  :address: smtp.zoho.com
  :port: 465
  :authentication: plain
  :user_name: admin@menochi.ir
  :password: menochiadmin810190501
  :authentication: login
  :ssl: true
  :tls: true
  :enable_starttls_auto: true
production:
  :address: smtp.zoho.com
  :port: 465
  :authentication: plain
  :user_name: admin@menochi.ir
  :password: menochiadmin810190501
  :authentication: login
  :ssl: true
  :tls: true
  :enable_starttls_auto: true
